android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java
I had a problem when extending from FlutterFragmentActivity instead of FlutterActivity and it's because the requestCode in **startActivityForResult** is greater than 16 bits ( 65535) i changed it to 65030 and 65031.
=> update request code because it's greater than 16 bits

ios/flutter_appauth.podspec
Fixes iOS 13 compatibility
[OIDAuthState.authState fails to show browser on iOS 13](https://github.com/openid/AppAuth-iOS/issues/400)
=> Bump AppAuth-iOS dependency to fix iOS 13 compatibility

README.md
Minor documentation change to correct the return type of the token call.
=> doc: Token return changed to TokenReponse

flutter_appauth_platform_interface/lib/src/method_channel_flutter_appauth.dart
Fixes https://github.com/MaikuB/flutter_appauth/issues/86
=> [flutter_appauth_platform_interface] Fixes error on casting the tokenAdditionParameters property from calling token method

flutter_appauth/CHANGELOG.md, flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java, flutter_appauth/pubspec.yaml
See comment https://github.com/MaikuB/flutter_appauth/issues/131#issuecomment-685803908
**TODO:**
However, `fetchFromIssuer` doesn't accept a `ConnectionBuilder` parameter, so I cannot add insecure support for it.
=> [flutter_appauth] Fix allowInsecureConnections not effect when serviceConfigurationParameters is null

flutter_appauth/CHANGELOG.md, flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java, flutter_appauth/pubspec.yaml
This seems to crash apps when intent is null.
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_appauth])
=> [flutter_appauth] Check if intent is null in onActivityResult

flutter_appauth/README.md
I added another flutter tutorial which uses appauth_flutter, and reworked it so that other providers can easily add their tutorials.
Full disclosure: I'm an employee of FusionAuth. I didn't write the tutorial, but had a hand in getting it published. If this PR isn't cool to submit, no worries, just thought I'd suggest it.
=> [flutter_appauth] Reworked identity provider tutorial section, added FusionAuth.

flutter_appauth/CHANGELOG.md, flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java, flutter_appauth/ios/Classes/FlutterAppauthPlugin.m, flutter_appauth/pubspec.yaml, flutter_appauth_platform_interface/CHANGELOG.md, flutter_appauth_platform_interface/lib/src/authorization_parameters.dart, flutter_appauth_platform_interface/lib/src/authorization_request.dart, flutter_appauth_platform_interface/lib/src/authorization_token_request.dart, flutter_appauth_platform_interface/lib/src/method_channel_mappers.dart, flutter_appauth_platform_interface/pubspec.yaml, flutter_appauth_platform_interface/test/method_channel_flutter_appauth_test.dart
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_appauth])
=> [flutter_appauth][flutter_appauth_platform_interface] add responseMode as parameter for android and ios

flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java
Appauth fails to verify the id token and throws an `AuthorizationException` if you try to authorize against an auth service over http even if `allowInsecureConnections` is true. This PR simply sets the `skipIssuerHttpsCheck` flag to true if `allowInsecureConnections` is true.
=> [flutter_appauth] Skip https issuer check if allowInsecureConnections is true.

.gitignore, flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java
Added check in additionalParameters if there is ui_locales parameters, and set it in android with the new function which has been added at the last version of appAuth plugin otherwise application crashes
=> Support ui_locales parameters

flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java
A fix for https://github.com/MaikuB/flutter_appauth/issues/291#issue-1111841681
=> [flutter_appauth] Handle OpenID claims parameter correctly for authorization requests on Android

flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java, flutter_appauth/ios/Classes/FlutterAppauthPlugin.m, flutter_appauth_platform_interface/lib/src/authorization_token_response.dart, flutter_appauth_platform_interface/lib/src/method_channel_flutter_appauth.dart, flutter_appauth_platform_interface/lib/src/token_response.dart
I hope I did the iOS part right - this was my first encounter with Obj-C and I don't have a way to test it.
The Android part works fine for me, so there and in the Dart code shouldn't be any issue.
Fixes #295.
=> [flutter_appauth][flutter_appauth_platform_interface] fix: missing scopes in token response

flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java
This PR is to finish the fix started with the PR #228. This fix works fine for authorization, but on token refresh the HTTPS check error is triggered again.
=> [flutter_appauth] Skip HTTPS check for unsecure connections for attributes built 'onAttachedToEngine' method.

flutter_appauth/README.md
I've been reading over the docs quite a bit recently, and keep noticing these two typos. Thought I'd save newcomers a few seconds of confusion when copy-pasting the code block results in a compiler fail 🙂
=> [flutter_appauth] Fix minor typos in README

flutter_appauth/ios/flutter_appauth.podspec, flutter_appauth/macos/flutter_appauth.podspec
just moving the AppAuth dependency to 1.5.0.
1.4.0 made it impossible to use this package and the latest version of [google_sign_in](https://pub.dev/packages/google_sign_in) package in the same app... (google_sign_in required 1.5.0 and flutter_appauth required 1.4.0)
=>  [flutter_appauth] using AppAuth 1.5.0

flutter_appauth/README.md, flutter_appauth/ios/Classes/AppAuthIOSAuthorization.m, flutter_appauth/ios/Classes/FlutterAppAuth.h, flutter_appauth/ios/Classes/FlutterAppauthPlugin.m, flutter_appauth/macos/Classes/AppAuthMacOSAuthorization.m, flutter_appauth_platform_interface/lib/src/end_session_request.dart, flutter_appauth_platform_interface/lib/src/method_channel_mappers.dart, flutter_appauth_platform_interface/test/method_channel_flutter_appauth_test.dart
Hi,
at the moment it is possible to pass the option `preferEphemeralSession: true` to the sign in call, but not to the end session call. Therefore, before every logout a pop-up like this is shown to the user:
If no pop-up was displayed before the login, it would be nicer if there is also none before the logout. So, I added the functionality to set the `preferEphemeralSession` option also for the end session call.
It would be nice if this feature could be included into the library.
=> [flutter_appauth][flutter_appauth_platform_interface] Add preferEphemeralSession option to logout

flutter_appauth/README.md
Add as in the [AppAuth for Android documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md#capturing-the-authorization-redirect) the alternative way to define the redirect scheme, which allows deep link flutter and OAuth 2.
=> [flutter_appauth] docs: add alternative for appAuthRedirectScheme

flutter_appauth/README.md
Hi all, The Asgardeo team has written an article[1] explaining how to connect a Flutter application with Asgardeo using the flutter_appauth library. Asgardeo is WSO2's SaaS Customer IAM (CIAM) solution.
I am a member of the Asgardeo development team and I took the initiative to create this PR to propose adding the aforementioned article to your main documentation.I understand that the decision to merge this PR rests with your team, so please feel free to share your thoughts and suggestions. I simply wanted to suggest the idea.
Thank you for your consideration.
References
[1] https://wso2.com/asgardeo/resources/authenticate-users-into-flutter-applications-using-asgardeo/
=> [flutter_appauth] Updated tutorials section to add Asgardeo.

flutter_appauth/macos/Classes/AppAuthMacOSAuthorization.m
[flutter_appauth] fix MacOs auth. Without that it opens regular Safari browser and can't return back.
=> [flutter_appauth] use initWithPresentingWindow to fix deprecation warning

flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java
on Android Ii user does logout and while logging out user closes the browser and go background and come back, the app crashes. It happens because flutter activity waits for intent not to be null, but it is null. We need to add null check on activity result method on Android. 
Related issue: https://github.com/MaikuB/flutter_appauth/issues/459#issuecomment-1865485929
=> [flutter_appauth] Fix for logout crash while app is on background

flutter_appauth/README.md
Added information about how to handle the possible data leak on iOS due to the storage of the token in the cache.db file
Follow up of a previous PR > https://github.com/MaikuB/flutter_appauth/pull/463
=> [flutter_appauth] Update README.md

flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java
Currently, if there are no browser installed on the device, the underlying plugin AppAuth-Android will throw an ActivityNotFoundException which crashes the Flutter application. This was for instance reported here: https://github.com/MaikuB/flutter_appauth/issues/168
You can reproduce the error by running the example app on any emulator without any installed browsers (disable the default Chrome in Settings - Apps - Chrome) and trying to login.
This fixes the error by catching the ActivityNotFoundException and returning a PlattformException.
=> [flutter_appauth] Catch native ActivityNotFoundException

flutter_appauth/CHANGELOG.md, flutter_appauth/example/lib/main.dart, flutter_appauth/lib/src/flutter_appauth.dart, flutter_appauth/pubspec.yaml, flutter_appauth_platform_interface/CHANGELOG.md, flutter_appauth_platform_interface/lib/src/flutter_appauth_platform.dart, flutter_appauth_platform_interface/lib/src/method_channel_flutter_appauth.dart, flutter_appauth_platform_interface/pubspec.yaml, flutter_appauth_platform_interface/test/method_channel_flutter_appauth_test.dart
=> [various] updated methods to return non-nullable types

flutter_appauth/CHANGELOG.md, flutter_appauth/android/src/main/AndroidManifest.xml
=> [flutter_appauth] specify theme for RedirectUriReceiverActivity

flutter_appauth_platform_interface/CHANGELOG.md, flutter_appauth_platform_interface/lib/src/errors.dart, flutter_appauth_platform_interface/pubspec.yaml
Removed the need for having the parameters of the `FlutterAppAuthPlatformErrorDetails` constructor being required as they're nullable
=> [flutter_appauth_platform_interface] made FlutterAppAuthPlatformErrorDetails constructor parameters optional

flutter_appauth/example/lib/main.dart, flutter_appauth/ios/Classes/AppAuthIOSAuthorization.h, flutter_appauth/ios/Classes/AppAuthIOSAuthorization.m, flutter_appauth/ios/Classes/FlutterAppAuth.h, flutter_appauth/ios/Classes/FlutterAppAuth.m, flutter_appauth/ios/Classes/FlutterAppauthPlugin.m, flutter_appauth/ios/Classes/OIDExternalUserAgentIOSSafariViewController.h, flutter_appauth/ios/Classes/OIDExternalUserAgentIOSSafariViewController.m, flutter_appauth/lib/flutter_appauth.dart, flutter_appauth/macos/Classes/AppAuthMacOSAuthorization.m, flutter_appauth_platform_interface/lib/flutter_appauth_platform_interface.dart, flutter_appauth_platform_interface/lib/src/authorization_parameters.dart, flutter_appauth_platform_interface/lib/src/authorization_request.dart, flutter_appauth_platform_interface/lib/src/authorization_token_request.dart, flutter_appauth_platform_interface/lib/src/end_session_request.dart, flutter_appauth_platform_interface/lib/src/external_agent_type.dart, flutter_appauth_platform_interface/lib/src/method_channel_mappers.dart, flutter_appauth_platform_interface/test/method_channel_flutter_appauth_test.dart
**This fixes this issue:**
#538 
Implemented support for SFSafariController on iOS so that user can choose between `ASWebAuthenticationSession`, `EphemeralSession` and `SFSafariViewController`. 
**Reason**:
`ASWebAuthenticationSession` is having a displaying bug on iOS which would show "sign in" instead of "sign out" when user logs out.
However, `EphemeralSession` is not fulfilling our requirement because it is using a private browser which doesn't save the cache. So user has to input the password every time when they login. `SFSafariViewController` would be the better choice between these three because it doesn't show the alert and keep the cache at the same time.
**Additional:**
To implement these changes, I had to modify the `flutter_appauth_platform_interface`. The changes are in the …
=> Implement support for SFSafariController on iOS

flutter_appauth/CHANGELOG.md, flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java
=> [flutter_appauth] added logic to recreate AuthorizationService objects if disposed but were needed

flutter_appauth/README.md
fix typo
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_appauth])
=> [flutter_appauth] fix typo in README.md

.github/workflows/validate.yml, flutter_appauth/CHANGELOG.md, flutter_appauth/android/build.gradle, flutter_appauth/example/android/app/build.gradle, flutter_appauth/example/android/build.gradle, flutter_appauth/example/android/gradle/wrapper/gradle-wrapper.properties, flutter_appauth/example/android/settings.gradle, flutter_appauth/example/pubspec.yaml, flutter_appauth/pubspec.yaml, flutter_appauth_platform_interface/CHANGELOG.md, flutter_appauth_platform_interface/pubspec.yaml
Migrated example app to use plugin DSL. Plugin and platform interface has minimum SDK versions bumped to Flutter 3.19/Dart 3.3 accordingly as aligns with when they're recommended versions as described in the [Flutter docs](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)
As part of this the Android side of the plugin has the `compileSdkVersion` bumped to 33 and AGP to 8.0.1 to align with what's used to build the AppAuth Android SDK itself.
The AGP version of the example app is also bumped to 8.6.0 to align with the [minimum tooling versions](https://developer.android.com/build/releases/gradle-plugin#api-level-support) to allow the example to compile and target using API 35
=> [various] updates to migrate example app to use plugin DSL
